### ISSUE TITLE
Allow switching dtb in extlinux.conf for nvidia devices

### ISSUE THREAD

**Issue by acostach** [balena-io/balena-supervisor#1207]
This feature is related to switching dtbs from dashboard , in a similar way to how it's done for the RPI. Therefore a similar property
called DTB needs to be added to the device section in the dashboard. User will fill in the dtb file name in the dashboard, and the supervisor needs to check
if the file exists in the current active rootfs in /boot/, and modify /boot/extlinux/extlinux.conf
to specify the dtb. Example:

LABEL primary
  MENU LABEL primary Image
  LINUX /boot/Image
  FDT /boot/mycustomdtb.dtb <-- this path should be added, or replaced in extlinux.conf
  APPEND ${cbootargs} ${resin_kernel_root} ro rootwait sdhci_tegra.en_boot_part_access=1 ${os_cmdline}

The extlinux.conf file and the dtbs are located in the current active rootfs. This feature is added in L4T 32.3.1, and is available for all jetson device types.

HQ: https://github.com/balena-io/balena/issues/2166

**Comment by AeroNotix** [comment]
Will this feature allow users to upload a custom DTB into the dashboard and have that set as the device-tree?

**Comment by CameronDiver** [comment]
@AeroNotix At least not in the first iteration, the dtb must be present in the host OS I believe.

**Comment by AeroNotix** [comment]
From what @acostach mentioned it seemed like that could be the case that users would be able to upload their own.

Even if this isn't the initial implementation it would be a great addition - the DTB file the user uploads could be injected into the img.zip file. For example, there's a feature I haven't used myself, but is documented to work where the dtb is just appended to the Linux zImage, and Linux will use this appended device-tree.

In addition to the above feature, it would be very useful if somehow the DTS/DTSI files were hosted alongside the DTB files such that users could understand from where the resulting DTB files were created as it would be a big service to the TX2 community as a whole because Nvidia is..... lets just say "lacking", in this area, with many (including myself at one point) scouring documentation and vague forum posts to build the proper device tree.

**Comment by thgreasi** [comment]
After checking with Rich, it seems that we are going to call it `RESIN_HOST_EXTLINUX_fdt`.

**Comment by AeroNotix** [comment]
@acostach How's this feature going? Interested to start testing it.

**Comment by CameronDiver** [comment]
Hey @AeroNotix we have a plan to start moving forward with this, and should have more news fairly soon.

**Comment by acostach** [comment]
Adding discussion from the new arch call topic and in fd here for consistency:

extlinux.conf file should not be updated anymore, instead an uboot environment file should be used by the supervisor to place the extra kernel cmdline args and device tree filename. This uboot file is named extra_uEnv.txt and is now provided by the OS in the boot partition. The jetson device layer also uses the dtb provided by extra_uEnv.txt file, because the values it stores are loaded in uboot's environment.

**Comment by acostach** [comment]
@20k-ultra , we need to also note that the supervisor should NOT reboot the board due to any configuration change while HUP is running, or right after a reboot into the new OS, if the rollback files were not cleared yet.
