### ISSUE TITLE
Documentation reference broken?

### ISSUE THREAD

**Issue by pranasziaukas** [balena-io/balena-supervisor#1607]
https://github.com/balena-io/balena-supervisor/blob/master/docs/upgrades.md opens when "IMPROVE THIS DOC" is clicked in https://www.balena.io/docs/reference/supervisor/supervisor-upgrades/ but it's obvious that the contents don't match at all.

Is `docs/upgrades.md` some ancient version that needs to be removed?

**Comment by 20k-ultra** [comment]
I wouldn't say ancient but it is legacy now that we support self serve updates via the dashboard. Since this repository does not require the dashboard and is just a process on the device that uses a cloud API I will opt to have Supervisor upgrade documentation in the docs repo which covers other dashboard actions.

Closing in favour of https://github.com/balena-io/docs/issues/1602.
